apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: how-about-some-tests-y6ze
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: how-about-some-tests-y6ze
    app.kubernetes.io/part-of: how-about-some-tests
  name: how-about-some-tests-y6ze
  namespace: eric-deandrea-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: how-about-some-tests-y6ze
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: how-about-some-tests-y6ze
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:eric-deandrea-tenant-how-about-some-tests-y6ze
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
