apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: how-about-some-tests-y6ze
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: how-about-some-tests-y6ze
    app.kubernetes.io/part-of: how-about-some-tests
  name: how-about-some-tests-y6ze
  namespace: eric-deandrea-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: how-about-some-tests-y6ze
status:
  loadBalancer: {}
